title: My Blog
author: bahd-helts
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my first Jekyll blog!

theme: minima

# Optional: URL settings (not strictly needed right now)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bahd-helts.github.io"
